// Product data with image mappings
const products = [
  // Smart Home
  {
    id: 'sh001',
    name: 'Nebula Smart Hub',
    code: 'NSH-2024',
    status: 'In Stock',
    quantity: 120,
    price: 129.99,
    description: 'The central nervous system of your smart home. Control lights, thermostats, and security systems with your voice or our intuitive app. Features seamless integration with over 1000 smart devices.',
    imageUrl: 'images/smart-hub.jpg',
    features: ['Voice Control', 'Universal Compatibility', 'AI-driven Automation', 'Energy Saving Mode'],
  },
  {
    id: 'sh002',
    name: 'Aura Ambient Lighting',
    code: 'AAL-V3',
    status: 'In Stock',
    quantity: 300,
    price: 49.99,
    description: 'Transform any room with over 16 million colors. Sync with your music, movies, or games for an immersive experience. Easy to install and expand.',
    imageUrl: 'images/smart-light.jpg',
    features: ['16 Million Colors', 'Music & Video Sync', 'Scheduled Routines', 'App & Voice Control'],
  },
  {
    id: 'sh003',
    name: 'Guardian Door Lock',
    code: 'GDL-PRO',
    status: 'Pre-order',
    quantity: 0,
    price: 249.99,
    description: 'Keyless entry for your home. Features biometric fingerprint scanning, a digital keypad, and remote access via our app. Grant temporary access to guests from anywhere.',
    imageUrl: 'images/smart-lock.jpg',
    features: ['Biometric Sensor', 'Remote Access', 'Guest Access Codes', 'Auto-Lock Functionality'],
  },
  // Wearables
  {
    id: 'wt001',
    name: 'Chrono-Link Smartwatch',
    code: 'CLW-S5',
    status: 'In Stock',
    quantity: 85,
    price: 399.99,
    description: 'More than just a watch. Track your fitness, manage notifications, and make payments, all from your wrist. Features a stunning always-on AMOLED display and 7-day battery life.',
    imageUrl: 'images/smartwatch.jpg',
    features: ['AMOLED Display', 'Advanced Health Tracking', 'NFC Payments', '7-Day Battery Life'],
  },
  {
    id: 'wt002',
    name: 'SonicWave Earbuds',
    code: 'SWE-X1',
    status: 'In Stock',
    quantity: 250,
    price: 179.99,
    description: 'Crystal-clear audio with adaptive noise cancellation. Enjoy up to 30 hours of playtime with the charging case. Ergonomically designed for all-day comfort.',
    imageUrl: 'images/earbuds.jpg',
    features: ['Adaptive Noise Cancellation', '30-Hour Battery', 'Studio-Quality Sound', 'Comfortable Fit'],
  },
  {
    id: 'wt003',
    name: 'Neuro-Band',
    code: 'NB-FIT',
    status: 'Out of Stock',
    quantity: 0,
    price: 129.99,
    description: 'A minimalist fitness tracker that monitors sleep, activity, and stress levels. Provides personalized insights to help you optimize your well-being.',
    imageUrl: 'images/fitness-band.jpg',
    features: ['24/7 Health Monitoring', 'Sleep & Stress Tracking', 'Personalized Insights', 'Water Resistant'],
  },
  // Drones
  {
    id: 'dr001',
    name: 'Sky-Watcher Drone',
    code: 'SWD-4K',
    status: 'In Stock',
    quantity: 40,
    price: 799.99,
    description: 'Capture breathtaking aerial footage with a 4K HDR camera. 30-minute flight time, intelligent flight modes, and a 5km transmission range.',
    imageUrl: 'images/drone-4k.jpg',
    features: ['4K HDR Video', '3-Axis Gimbal', 'Intelligent Flight Modes', '30-Min Flight Time'],
  },
  {
    id: 'dr002',
    name: 'Hornet Racing Drone',
    code: 'HRD-FPV',
    status: 'In Stock',
    quantity: 25,
    price: 499.99,
    description: 'Experience the thrill of FPV racing. Reach speeds of up to 140 km/h with this agile and durable racing drone. Perfect for both beginners and pros.',
    imageUrl: 'images/racing-drone.jpg',
    features: ['140 km/h Top Speed', 'FPV Goggles Included', 'Carbon Fiber Frame', 'Modular Design'],
  },
  {
    id: 'dr003',
    name: 'Nano-Scout Mini Drone',
    code: 'NSMD-1',
    status: 'In Stock',
    quantity: 150,
    price: 89.99,
    description: 'A fun and easy-to-fly mini drone that fits in the palm of your hand. Perfect for indoor flying and learning the basics of drone piloting.',
    imageUrl: 'images/mini-drone.jpg',
    features: ['Palm-sized', 'Altitude Hold', 'One-Key Takeoff/Landing', 'Propeller Guards'],
  },
  // Audio
  {
    id: 'au001',
    name: 'Resonance Speaker',
    code: 'RS-360',
    status: 'In Stock',
    quantity: 90,
    price: 299.99,
    description: '360-degree sound in a sleek, portable package. Connect via Bluetooth or Wi-Fi for multi-room audio. Water-resistant design for music anywhere.',
    imageUrl: 'images/bluetooth-speaker.jpg',
    features: ['360° Sound', 'Bluetooth & Wi-Fi', 'IPX7 Water-Resistant', '12-Hour Battery'],
  },
  {
    id: 'au002',
    name: 'Echo-Bar Soundbar',
    code: 'EBS-ATMOS',
    status: 'In Stock',
    quantity: 60,
    price: 599.99,
    description: 'Bring the cinema home with Dolby Atmos surround sound. This soundbar and wireless subwoofer combo delivers powerful, immersive audio for your movies and games.',
    imageUrl: 'images/soundbar.jpg',
    features: ['Dolby Atmos', 'Wireless Subwoofer', '4K HDR Passthrough', 'Dialogue Enhancement'],
  },
  {
    id: 'au003',
    name: 'Studio Pro Headphones',
    code: 'SPH-NC',
    status: 'In Stock',
    quantity: 110,
    price: 349.99,
    description: 'Over-ear headphones for the true audiophile. Industry-leading noise cancellation, high-resolution audio, and plush comfort for long listening sessions.',
    imageUrl: 'images/headphones.jpg',
    features: ['High-Res Audio', 'Active Noise Cancellation', '30-Hour Battery', 'Premium Comfort'],
  },
  // Gaming
  {
    id: 'gm001',
    name: 'Vortex Gaming Console',
    code: 'VGC-X',
    status: 'Pre-order',
    quantity: 0,
    price: 499.99,
    description: 'The next generation of gaming is here. Experience lightning-fast load times, 4K gaming at 120fps, and a revolutionary new controller with haptic feedback.',
    imageUrl: 'images/gaming-console.jpg',
    features: ['4K 120fps Gaming', 'Ultra-Fast SSD', 'Haptic Feedback Controller', 'Ray Tracing Support'],
  },
  {
    id: 'gm002',
    name: 'Phantom Mechanical Keyboard',
    code: 'PMK-RGB',
    status: 'In Stock',
    quantity: 200,
    price: 159.99,
    description: 'Gain the competitive edge with this fully customizable mechanical keyboard. Features swappable optical switches, per-key RGB lighting, and a durable aluminum frame.',
    imageUrl: 'images/gaming-keyboard.jpg',
    features: ['Optical Switches', 'Per-Key RGB', 'Aircraft-Grade Aluminum', 'Programmable Macros'],
  },
  {
    id: 'gm003',
    name: 'Wraith Gaming Mouse',
    code: 'WGM-PRO',
    status: 'In Stock',
    quantity: 180,
    price: 89.99,
    description: 'An ultra-lightweight, high-performance gaming mouse. Equipped with a 20K DPI sensor for pixel-perfect accuracy and a flexible, drag-free cable.',
    imageUrl: 'images/gaming-mouse.jpg',
    features: ['20,000 DPI Sensor', 'Ultra-Lightweight Design', 'PTFE Glide Feet', 'Onboard Memory'],
  },
];

const categories = [
  {
    id: 'cat01',
    name: 'Smart Home',
    description: 'Automate your life with our range of smart home devices.',
    products: products.filter(p => p.id.startsWith('sh')),
  },
  {
    id: 'cat02',
    name: 'Wearable Tech',
    description: 'Stay connected and track your health with our stylish wearables.',
    products: products.filter(p => p.id.startsWith('wt')),
  },
  {
    id: 'cat03',
    name: 'Drones & Aerial',
    description: 'Capture stunning views from the sky with our high-tech drones.',
    products: products.filter(p => p.id.startsWith('dr')),
  },
  {
    id: 'cat04',
    name: 'Premium Audio',
    description: 'Immerse yourself in sound with our high-fidelity audio gear.',
    products: products.filter(p => p.id.startsWith('au')),
  },
  {
    id: 'cat05',
    name: 'Gaming Gear',
    description: 'Level up your game with our professional-grade peripherals.',
    products: products.filter(p => p.id.startsWith('gm')),
  },
];
